Replace 'wait i' with 'wait q[..],i' syntax v1
QE-Lab/libqasm pull request #137
Opened 2021-12-21 16:08 UTC by rknegjens

This PR is part of the cQASM 1.0 multiple measurements update for Quantum Inspire, which specifies following modification to `wait` instruction.

> A wait gate may be used to explicitly tell the scheduler to idle the qubit it operates on for the given number of cycles. For example, if you'd write
> 
> ```
> prep_z q[0]
> wait q[0], 100
> measure q[0]
> ```
> 
> the measurement must start at least 100 cycles after the prep_z completes. wait q[0,1] follows the single-gate-multiple-qubit rule, expanding to wait q[0]; wait q[1]. Thus, the wait blocks are independent.

**Note that this breaks compatibility with cQASM v1.0**, which is an argument for **not** merging it into develop branch.

2021-12-21 16:10 UTC, rknegjens commented
@QFer please review this PR for new `wait` syntax, and note warning above: this will break compatibiltiy with v1 syntax, so perhaps better to leave in separate branch for quantum inspire?

2021-12-22 09:46 UTC, wvlothuizen commented
Not sure of the context of this PR, but note that the intended functionality already works with OpenQL 0.10.0 with the 'new' cQasm reader (as now used for Transmon setups with cQasm 1.2). See the special handling in https://github.com/QE-Lab/OpenQL/blob/develop/src/ql/ir/cqasm/read.cc#L715

Even the old cQasm reader overrides the libqasm gateset, see https://github.com/QE-Lab/OpenQL/blob/develop/src/ql/ir/compat/detail/cqasm_reader.cc#L590

One note on the PR itself: if the wait syntax is changed, the documentation should be as well (see https://libqasm.readthedocs.io/en/latest/cq1-instructions.html)

2021-12-22 10:20 UTC, rknegjens commented
@wvlothuizen for context for this PR best to check with @oschusler or @QFer. Changes were requested for cQASM v1, as used by Quantum Inspire, which to my knowledge also doesn't use OpenQL.

> One note on the PR itself: if the wait syntax is changed, the documentation should be as well 

Yes, missed this, thanks!

2021-12-22 15:04 UTC, jvansomeren commented
cQASM v1 is mentioned.
As far as I know, there is only cQASM 1.0, cQASM 1.1 and cQASM 1.2.
What is meant by cQASM v1?

Op 22 dec. 2021, om 11:20 heeft Rob Knegjens ***@***.******@***.***>> het volgende geschreven:



@wvlothuizen<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_wvlothuizen&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=kNdT9ewT6pQdYFkBLR_5-ZqsrSTk7k5Hdd7MSC_Vnzg&m=1MhJ8sQGqtyrhJjHeL4AeE670Y-iuFaCdaN0vJ2U4LM&s=RPH7BS_bNBa1Hrxto4_3e_DEUY9Ug-aRNzW7VOj0BmI&e=> for context for this PR best to check with @oschusler<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_oschusler&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=kNdT9ewT6pQdYFkBLR_5-ZqsrSTk7k5Hdd7MSC_Vnzg&m=1MhJ8sQGqtyrhJjHeL4AeE670Y-iuFaCdaN0vJ2U4LM&s=OtQqD-WJ7G8vbsDPvZJSsuFa8IZrF_vQZ9neEZq6hXM&e=> or @QFer<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_QFer&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=kNdT9ewT6pQdYFkBLR_5-ZqsrSTk7k5Hdd7MSC_Vnzg&m=1MhJ8sQGqtyrhJjHeL4AeE670Y-iuFaCdaN0vJ2U4LM&s=N5B1EjwekmF8BhEzgOlitWr2zOzXZV8cuHOfVwI6R9U&e=>. Changes were requested for cQASM v1, as used by Quantum Inspire, which to my knowledge also doesn't use OpenQL.

One note on the PR itself: if the wait syntax is changed, the documentation should be as well

Yes, missed this, thanks!

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_QE-2DLab_libqasm_pull_137-23issuecomment-2D999457944&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=kNdT9ewT6pQdYFkBLR_5-ZqsrSTk7k5Hdd7MSC_Vnzg&m=1MhJ8sQGqtyrhJjHeL4AeE670Y-iuFaCdaN0vJ2U4LM&s=Dy0_BoskgL4IkzGVOsJcDdxnEd837C1wozUbkbnffQE&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEDTBNVHMMF4PPNSJVLCLL3USGQ6JANCNFSM5KQRADKQ&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=kNdT9ewT6pQdYFkBLR_5-ZqsrSTk7k5Hdd7MSC_Vnzg&m=1MhJ8sQGqtyrhJjHeL4AeE670Y-iuFaCdaN0vJ2U4LM&s=76VvY36rCvRwWL85hNV6g2m2L3IyxGX8mn3PmWdXlqA&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=kNdT9ewT6pQdYFkBLR_5-ZqsrSTk7k5Hdd7MSC_Vnzg&m=1MhJ8sQGqtyrhJjHeL4AeE670Y-iuFaCdaN0vJ2U4LM&s=TL3q5LPrdNEb7QnwCq9eaMCz_pc59NH2G13BXtU8nlg&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=kNdT9ewT6pQdYFkBLR_5-ZqsrSTk7k5Hdd7MSC_Vnzg&m=1MhJ8sQGqtyrhJjHeL4AeE670Y-iuFaCdaN0vJ2U4LM&s=aPp9auC0L4YvE9FsYlobNEwEi-HaRk7YAVitWn0k6C4&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2021-12-22 16:32 UTC, rknegjens commented
@jvansomeren by v1 I mean 1.0

2021-12-22 18:28 UTC, jvansomeren commented
Libqasm is the library that supports reading cQASM. In OpenQL the cqasmreader uses libqasm to read the cqasm file which produces an AST (abstract syntax tree); the cqasmreader subsequently uses the AST to create OpenQL IR.
cQASM comes in two flavors: with a built-in gate set and with a configurable gate set. In summer 2021 libqasm was rewritten to support these two flavors. OpenQL uses the cQASM configurable gate set flavor and usually 'wait' is defined in the configuration as an ordinary gate; this configuration allows target-specific gates to be supported. This PR concerns the built-in gate set, and especially the 1.0 definition. Note that compatibility is defined from 1.0 to 1.1 and then to 1.2 so when 1.0 is changed, 1.1 and 1.2 should be updated as well.
To prevent an incompatible change, wouldn't it be a solution to support both, the wait i and the wait q[...], i syntax in 1.0?

2021-12-23 15:31 UTC, jvansomeren commented
Wouter Vlothuizen commented:

I'm afraid changing the language definition in one spot tends to spill over to other places, e.g. OpenQL, so any such changes should be carefully considered, especially if the proposed syntax should eventually work on OpenQL/Transmons (should it?).

The definition "wait i" in libqasm is based on the original language specification in https://arxiv.org/abs/1805.09607, but is pretty useless because of the lack op a qubit parameter. Because of that, OpenQL uses the (runtime) configuration mechanism of libqasm to add the syntax originally proposed here ("wait q[], i"). Additionally, the OpenQL scheduler treats waits on multiple qubits as a barrier.
OpenQL also adds a "skip" instruction which adds a delay without special scheduler treatment.

So I would advice against adding "delay", and follow the method used by OpenQL, either by changing libqasm, or by providing a user defined gateset to libqasm the way OpenQL does.

2022-01-18 09:46 UTC, QFer requested changes

2022-01-18 09:46 UTC, QFer commented on src/library/qasm_ast.hpp
> +            Operation(const std::string type, const int waitInt, Qubits qubits_involved)
```suggestion
            Operation(const std::string type, Qubits qubits_involved, const int wait_int)
```

2022-01-18 09:46 UTC, QFer commented on src/library/qasm_ast.hpp
> +            // the int is the first argument (FIXME?)
This can be fixed. Polymorphism is about the signature of the methods.
The difference here is the (const int) and the (const double) parameter in the method on line 138.
The caller should make it more explicit what the type of the third parameter is by (in this case) doing a cast of the third parameter. So instead of doing the ambiguous calls for SingleQubitInt and SingleQubitReal in qasm_new_to_old.hpp with parameters:
instruction.operands[1]->as_const_int()->value
instruction.operands[1]->as_const_real()->value

we cast them to the correct type to make them non-ambiguous:

(const int)instruction.operands[1]->as_const_int()->value
(const real)instruction.operands[1]->as_const_real()->value

2022-01-18 09:46 UTC, QFer commented on src/library/qasm_new_to_old.hpp
> +                instruction.operands[1]->as_const_int()->value,
```suggestion
                (const int)instruction.operands[1]->as_const_int()->value,
```
to solve the ambiguity.
Also this parameter should be the third parameter.

2022-01-18 09:46 UTC, QFer commented on src/library/qasm_ast.hpp
> +                wait_time_ = waitInt;
```suggestion
                wait_time_ = wait_int;
```
camelCase waitInt is inconsistent here. Turn into snake_case

2022-01-18 09:46 UTC, QFer commented on src/library/qasm_semantic.hpp
> +                //else if (type_ == "skip" || type_ == "wait" || type_ == "display" || type_ == "display_binary" || type_ == "not" || type_ == "load_state")
remove this line

2022-01-18 09:46 UTC, QFer commented on src/library/qasm_ast.hpp
> +
line #176 should be changed from:
// Wait and Skip commands
to
// Skip command

2022-01-18 15:43 UTC, jvansomeren requested changes
With respect to the documentation:

The definition text is ambiguous in the sense that it doesn't make clear that the waits on the individual qubits are independent, i.e. follow the SGMQ handling, so something like:

For each of the specified qubits, wait for all previous instructions involving the specified qubit to finish, and then wait at least the given number of cycles before starting a next instruction involving the specified qubit. In essence, this acts as a no-op instruction for the specified qubit with the specified duration in cycles. So the individual waits on each of the qubits are independent of each other, following the regular single-gate-multiple-qubit rules.

2022-01-18 15:53 UTC, jvansomeren commented on src/library/qasm_ast.hpp
> +
In src/library/qasm_ast.hpp you mention: TODO also print qubits. Please do!

2022-01-18 15:54 UTC, jvansomeren commented on src/library/qasm_ast.hpp
> +                    // TODO also print qubits
In src/library/qasm_ast.hpp line 386 you mention: TODO also print qubits. Please do!

2022-01-18 16:11 UTC, jvansomeren requested changes
So: documentation to be explicit about SGMQ rules. See earlier comment.
And: also print qubits when printing wait gate

2022-01-19 08:05 UTC, wvlothuizen reviewed
No additional comments from my side

2022-01-19 09:40 UTC, jvansomeren commented
So I wait for Fer to do the requested changes, then review those.

Op 19 jan. 2022, om 09:05 heeft Wouter Vlothuizen ***@***.******@***.***>> het volgende geschreven:



@wvlothuizen commented on this pull request.

No additional comments from my side

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_QE-2DLab_libqasm_pull_137-23pullrequestreview-2D856424684&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=kNdT9ewT6pQdYFkBLR_5-ZqsrSTk7k5Hdd7MSC_Vnzg&m=M4ZV9rC7_vaxRJaYhj3DpKJ-5v2aX8XLDOSaRk-wEjs&s=aoWZlKMTxoCVCxvpnw6iuY7DhgTDMjscp0FIMsVCZws&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEDTBNQSGXCN2ZDWMX7YLR3UWZWEBANCNFSM5KQRADKQ&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=kNdT9ewT6pQdYFkBLR_5-ZqsrSTk7k5Hdd7MSC_Vnzg&m=M4ZV9rC7_vaxRJaYhj3DpKJ-5v2aX8XLDOSaRk-wEjs&s=koP6aDW9YEf17SUZ_OeqXP3SlfaXCQzznyAhQh1alTo&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=kNdT9ewT6pQdYFkBLR_5-ZqsrSTk7k5Hdd7MSC_Vnzg&m=M4ZV9rC7_vaxRJaYhj3DpKJ-5v2aX8XLDOSaRk-wEjs&s=pxgHn4OhDfT4Q8-Ez2ZV4O0ldxGPQmB0TrYF9HCZ4Sk&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=kNdT9ewT6pQdYFkBLR_5-ZqsrSTk7k5Hdd7MSC_Vnzg&m=M4ZV9rC7_vaxRJaYhj3DpKJ-5v2aX8XLDOSaRk-wEjs&s=BPep9j1HjxwWb1FA6s6nEHjqn_5qZOvB3ZvVxw5EvI0&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-01-20 11:02 UTC, QFer commented on src/library/qasm_ast.hpp
> +                    // TODO also print qubits
Added printing the qubits

2022-01-20 11:02 UTC, QFer commented on src/library/qasm_ast.hpp
> +
Addressed

2022-01-20 11:02 UTC, QFer commented on src/library/qasm_ast.hpp
> +                wait_time_ = waitInt;
Change to snake_case

2022-01-20 11:03 UTC, QFer commented on src/library/qasm_new_to_old.hpp
> +                instruction.operands[1]->as_const_int()->value,
Solved ambiguity

2022-01-20 11:03 UTC, QFer commented on src/library/qasm_ast.hpp
> +            // the int is the first argument (FIXME?)
fixed

2022-01-20 11:03 UTC, QFer commented on src/library/qasm_ast.hpp
> +            Operation(const std::string type, const int waitInt, Qubits qubits_involved)
Changed

2022-01-20 12:04 UTC, jvansomeren requested changes
Why was in doc/source/cq1-instructions.rst the 

> barrier <qubit-ref>

 changed into 

> barrier <qubit>

?
Can the barrier still be called with a list of qubits?
Otherwise, we lose functionality.

2022-01-20 12:23 UTC, QFer commented
> Why was in doc/source/cq1-instructions.rst the
> 
> > barrier <qubit-ref>
> 
> changed into
> 
> > barrier <qubit>
> 
> ? Can the barrier still be called with a list of qubits? Otherwise, we lose functionality.

The barrier is implemented as:
"barrier <qubit>", just like "h <qubit>", "i <qubit>", "wait <qubit>, i" etc.
<qubit-ref> was inconsistent with the documentation for the other gates.
@jvansomeren

2022-01-25 14:20 UTC, jvansomeren commented
I propose to keep the barrier syntax allowing multiple qubits.
An explicit barrier on a single qubit makes no sense; it is implied at the start of every gate on that qubit.
There must be a misunderstanding here.
With taking out the wait i, and by only allowing wait <qubits>, i which has SGMQ semantics
there is otherwise to way to have a synchronized barrier between multiple qubits,
i.e. in which the execution of gates for one qubit waits until execution of gates for the other qubits have completed, and vice-versa

2022-01-31 16:05 UTC, jvansomeren approved these changes

2022-01-31 16:11 UTC, wvlothuizen approved these changes

2022-02-01 07:14 UTC, QFer approved these changes

2022-02-01 07:14 UTC, merged